data:
  image: "blijblijblij/base"
  volumes:
    - "~/.docker-volumes/dev/mysqldb/:/var/lib/mysql"
    - "~/.docker-volumes/dev/mysqlinstall/:/install"
    - "~/.docker-volumes/dev/postgresqldb/:/var/lib/postgresql/data/"
    - "~/.docker-volumes/dev/mongodb/:/data/db/"
dataslave:
  image: "blijblijblij/base"
  volumes:
    - "~/.docker-volumes/dev/mysqldbslave/:/var/lib/mysql"
haproxy:  
  image: "tutum/haproxy"
  environment:
    PORT: "8080"
    BALANCE: "source"
    #SSL_CERT: "YOUR_CERT_TEXT""
  expose:
    - "80"
  ports:
    - "81:80"
  links:
    - biserverleft
#    - biserverright
biserverleft:  
  image: "blijblijblij/pentaho:biserver-ce-5.3"
  expose:
    - "8080"
  ports:
    - "8080:8080"
  links:
    - postgresql
#biserverright:  
#  image: "blijblijblij/pentaho:biserver-ce-5.2"
#  expose:
#    - "8080"
#  ports:
#    - "8081:8080"
#  links:
#    - mysql
postgresql:
  image: "postgres:9.4"
  volumes_from:
    - "data"
  environment:
    POSTGRES_USER: "root"
    POSTGRES_PASSWORD: "password"
  expose:
    - "5432"
  ports:
    - "5432:5432"
#mysql:
#  image: "tutum/mysql:5.5"
#  volumes_from:
#    - "data"
#  environment:
#    MYSQL_USER: "root"
#    MYSQL_PASS: "password"
#    STARTUP_SQL: "/install/schema.sql"
#    REPLICATION_MASTER: "true"
#    REPLICATION_USER: "replica"
#    REPLICATION_PASS: "password"
#  expose:
#    - "3306"
#  ports:
#    - "3306:3306"
#mysqlslave:
#  image: "tutum/mysql:5.5"
#  volumes_from:
#    - "dataslave"
#  environment:
#    MYSQL_USER: "root"
#    MYSQL_PASS: "password"
#    REPLICATION_SLAVE: "true"
#    REPLICATION_USER: "replica"
#    REPLICATION_PASS: "password"
#  expose:
#    - "3306"
#  ports:
#    - "3307:3306"
#  links:
#    - mysql
#mongo:
#  image: "dockerfile/mongodb"
#  volumes_from:
#    - "data"
#  expose:
#    - "27017"
#  ports:
#    - "27017:27017"
#hadoop:
#  image: "sequenceiq/hadoop-ubuntu:2.6.0"
