data:
  image: "blijblijblij/base"
  volumes:
    - "~/.docker-volumes/dev/postgresqldb/:/var/lib/postgresql/data/"
haproxy:  
  image: "tutum/haproxy"
  environment:
    FRONTEND_PORT: "80"
    BACKEND_PORT: "8080"
    BALANCE: "source"
    #SSL_CERT: "YOUR_CERT_TEXT""
  expose:
    - "80"
  ports:
    - "80:80"
  links:
    - biserverleft
    - biserverright
biserverleft:  
  image: "blijblijblij/pentaho:biserver-ce-5.3"
  expose:
    - "8080"
  ports:
    - "8080"
  links:
    - postgresql
biserverright:  
  image: "blijblijblij/pentaho:biserver-ce-5.3"
  expose:
    - "8080"
  ports:
    - "8080"
  links:
    - postgresql
postgresql:
  image: "postgres:9.4"
  volumes_from:
    - "data"
  environment:
    POSTGRES_USER: "root"
    POSTGRES_PASSWORD: "password"
  expose:
    - "5432"
  ports:
    - "5432:5432"
